#### tensorflow基础API使用

In [2]:
# 使用tf.keras搭建回归模型，数据集使用加利福尼亚的房价预测
#导入必要的库即版本

import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras
#import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd,sklearn,tf,keras:
    print(module.__name__, module.__version__)

2.0.0-beta1
sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
matplotlib 2.2.3
numpy 1.16.4
pandas 0.23.4
sklearn 0.19.2
tensorflow 2.0.0-beta1
tensorflow.python.keras.api._v2.keras 2.2.4-tf


#### 常量

In [3]:
t = tf.constant([[1.,2.,3.],[4,5,6]])

# 索引操作
print(t)
print(t[:,1:])
print(t[...,1])

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor([2. 5.], shape=(2,), dtype=float32)


In [4]:
# 算子操作
print(t + 10)
print(tf.square(t))# 平方
print(t @ tf.transpose(t))   #矩阵乘法
# 1.0版本中需要session和run才可以得到具体的值
# 2.0默认eager execution打开，直接可以获得具体的值

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [5]:
# numpy转换
print(t.numpy()) # tf转numpy
print(np.square(t))
np_t = np.array([[1,2,3],[4,5,6]])
print(tf.constant(np_t))# numpy转tf

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [6]:
# 0维tfnsor    Scalars
t = tf.constant(2.718)
print(t.numpy())
print(t.shape)

2.718
()


字符串

In [8]:
# strings/单个字符串
t = tf.constant('cafe')
print(t)
print(tf.strings.length(t))
print(tf.strings.length(t, unit='UTF8_CHAR'))
print(tf.strings.unicode_decode(t, 'UTF8'))# 将字符串转换为UTF8编码

tf.Tensor(b'cafe', shape=(), dtype=string)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 99  97 102 101], shape=(4,), dtype=int32)


In [9]:
# string array 数组字符串
t = tf.constant(['cafe','coffee','咖啡'])
print(tf.strings.length(t, unit='UTF8_CHAR'))# 求数组中每个字符串的长度
r = tf.strings.unicode_decode(t, 'UTF8')
print(r)# 输出为RaggedTensor对象，即不完整的矩阵，第二维各行长度不一致/不规则

tf.Tensor([4 6 2], shape=(3,), dtype=int32)
<tf.RaggedTensor [[99, 97, 102, 101], [99, 111, 102, 102, 101, 101], [21654, 21857]]>


In [10]:
# RaggedTensor对象
r = tf.ragged.constant([[11,12],[21,22,23],[],[41]])
# 索引操作
print(r)
print(r[1])
print(r[1:2])

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41]]>
tf.Tensor([21 22 23], shape=(3,), dtype=int32)
<tf.RaggedTensor [[21, 22, 23]]>


In [16]:
# 拼接操作
r2 = tf.ragged.constant([[51,52],[],[71]])
print(tf.concat([r,r2],axis=0))# 横向拼接

# 纵向拼接需要维度有相同的行数
r3 = tf.ragged.constant([[13,14],[15],[],[42,43]])
print(tf.concat([r,r3],axis=1))

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41], [51, 52], [], [71]]>
<tf.RaggedTensor [[11, 12, 13, 14], [21, 22, 23, 15], [], [41, 42, 43]]>
